# **Alura Challenge DS - Semana 1**

Imports usados neste Notebook

In [ ]:
import pandas as pd

Carrengando e lendo as primeiras linhas do dataset

In [ ]:

url = "https://raw.githubusercontent.com/sthemonica/alura-voz/refs/heads/main/Dados/Telco-Customer-Churn.json"
dados = pd.read_json(url)

dados.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

#Entendendo quais informações o dataset possui

Informações gerais sobre as colunas e tipos de dados

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

Informações sobre cada Coluna/Dicionário

In [ ]:
dados.account[0]

{'Contract': 'One year',
 'PaperlessBilling': 'Yes',
 'PaymentMethod': 'Mailed check',
 'Charges': {'Monthly': 65.6, 'Total': '593.3'}}

In [ ]:
dados.customer[0]

{'gender': 'Female',
 'SeniorCitizen': 0,
 'Partner': 'Yes',
 'Dependents': 'Yes',
 'tenure': 9}

In [ ]:
dados.phone[0]

{'PhoneService': 'Yes', 'MultipleLines': 'No'}

In [ ]:
dados.internet[0]

{'InternetService': 'DSL',
 'OnlineSecurity': 'No',
 'OnlineBackup': 'Yes',
 'DeviceProtection': 'No',
 'TechSupport': 'Yes',
 'StreamingTV': 'Yes',
 'StreamingMovies': 'No'}

#Normalização dos dados

In [ ]:
customer_dados = pd.json_normalize(dados.customer)
customer_dados

      gender  SeniorCitizen Partner Dependents  tenure
0     Female              0     Yes        Yes       9
1       Male              0      No         No       9
2       Male              0      No         No       4
3       Male              1     Yes         No      13
4     Female              1     Yes         No       3
...      ...            ...     ...        ...     ...
7262  Female              0      No         No      13
7263    Male              0     Yes         No      22
7264    Male              0      No         No       2
7265    Male              0     Yes        Yes      67
7266    Male              0     Yes        Yes      63

[7267 rows x 5 columns]

In [ ]:
phone_dados = pd.json_normalize(dados.phone)
phone_dados

     PhoneService     MultipleLines
0             Yes                No
1             Yes               Yes
2             Yes                No
3             Yes                No
4             Yes                No
...           ...               ...
7262          Yes                No
7263          Yes               Yes
7264          Yes                No
7265          Yes                No
7266           No  No phone service

[7267 rows x 2 columns]

In [ ]:
internet_dados = pd.json_normalize(dados.internet)
internet_dados

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No
...,...,...,...,...,...,...,...
7262,DSL,Yes,No,No,Yes,No,No
7263,Fiber optic,No,No,No,No,No,Yes
7264,DSL,No,Yes,No,No,No,No
7265,DSL,Yes,No,Yes,Yes,No,Yes
7266,DSL,Yes,Yes,Yes,No,Yes,Yes

In [ ]:
account_dados = pd.json_normalize(dados.account, sep='')
account_dados

,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal
0,One year,Yes,Mailed check,65.60,593.3
1,Month-to-month,No,Mailed check,59.90,542.4
2,Month-to-month,Yes,Electronic check,73.90,280.85
3,Month-to-month,Yes,Electronic check,98.00,1237.85
4,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...
7262,One year,No,Mailed check,55.15,742.9
7263,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,Month-to-month,Yes,Mailed check,50.30,92.75
7265,Two year,No,Mailed check,67.85,4627.65
7266,Two year,No,Electronic check,59.00,3707.6

Concatenando os dataframes

In [ ]:
def normalize_json(dataframe):
    return_dataframe = pd.DataFrame()
    for column in list(dados.columns[2:]):
        dataframe_column = pd.json_normalize(dataframe[column])
        return_dataframe = pd.concat([return_dataframe, dataframe_column], axis=1)

    return pd.concat([dataframe[list(dados.columns[:2])], return_dataframe], axis=1)

In [ ]:
dados = normalize_json(dados)
dados

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [ ]:
for coluna in dados.columns:
    print('---')
    print(dados[coluna].value_counts())

---
customerID
0002-ORFBO    1
6614-VBEGU    1
6637-KYRCV    1
6635-MYYYZ    1
6635-CPNUN    1
             ..
3374-TTZTK    1
3374-PZLXD    1
3374-LXDEV    1
3373-YZZYM    1
9995-HOTOH    1
Name: count, Length: 7267, dtype: int64
---
Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64
---
gender
Male      3675
Female    3592
Name: count, dtype: int64
---
SeniorCitizen
0    6085
1    1182
Name: count, dtype: int64
---
Partner
No     3749
Yes    3518
Name: count, dtype: int64
---
Dependents
No     5086
Yes    2181
Name: count, dtype: int64
---
tenure
1     634
72    369
2     246
3     207
4     185
     ...
38     60
39     59
44     54
36     50
0      11
Name: count, Length: 73, dtype: int64
---
PhoneService
Yes    6560
No      707
Name: count, dtype: int64
---
MultipleLines
No                  3495
Yes                 3065
No phone service     707
Name: count, dtype: int64
---
InternetService
Fiber optic    3198
DSL            2488
No             1581
Name: count, dtype: int64
---
OnlineSecurity
No                     3608
Yes                    2078
No internet service    1581
Name: count, dtype: int64
---
OnlineBackup
No                     3182
Yes                    2504
No internet service    1581
Name: count, dtype: int64
---
DeviceProtection
No                     3195
Yes                    2491
No internet service    1581
Name: count, dtype: int64
---
TechSupport
No                     3582
Yes                    2104
No internet service    1581
Name: count, dtype: int64
---
StreamingTV
No                     2896
Yes                    2790
No internet service    1581
Name: count, dtype: int64
---
StreamingMovies
No                     2870
Yes                    2816
No internet service    1581
Name: count, dtype: int64
---
Contract
Month-to-month    4005
Two year          1743
One year          1519
Name: count, dtype: int64
---
PaperlessBilling
Yes    4311
No     2956
Name: count, dtype: int64
---
PaymentMethod
Electronic check             2445
Mailed check                 1665
Bank transfer (automatic)    1589
Credit card (automatic)      1568
Name: count, dtype: int64
---
Charges.Monthly
20.05     65
19.85     46
19.90     46
19.70     45
19.55     45
          ..
23.45      1
116.55     1
106.85     1
68.55      1
67.85      1
Name: count, Length: 1585, dtype: int64
---
Charges.Total
           11
20.2       11
19.75       9
19.55       9
19.9        9
           ..
272         1
1426.45     1
371.6       1
6786.4      1
3707.6      1
Name: count, Length: 6531, dtype: int64

In [ ]:
dados = dados[dados['Churn']!= '']
dados.reset_index(drop=True, inplace=True)

In [ ]:
dados.query('tenure == 0')[['Charges.Total', 'Charges.Monthly', 'tenure']]

     Charges.Total  Charges.Monthly  tenure
945                           56.05       0
1731                          20.00       0
1906                          61.90       0
2025                          19.70       0
2176                          20.25       0
2250                          25.35       0
2855                          73.35       0
3052                          25.75       0
3118                          52.55       0
4054                          80.85       0
5433                          19.85       0

In [ ]:
dados.query('tenure == 1')[['Charges.Total', 'Charges.Monthly', 'tenure']]

     Charges.Total  Charges.Monthly  tenure
17            72.1            72.10       1
19            25.1            25.10       1
25            30.5            30.50       1
48            44.3            44.30       1
63           19.85            19.85       1
...            ...              ...     ...
6980         25.05            25.05       1
7007          75.3            75.30       1
7021         20.05            20.05       1
7033          18.9            18.90       1
7036         70.15            70.15       1

[613 rows x 3 columns]

In [ ]:
dados[dados['Charges.Total'] == ' '][['Charges.Total', 'Charges.Monthly', 'tenure']]

     Charges.Total  Charges.Monthly  tenure
945                           56.05       0
1731                          20.00       0
1906                          61.90       0
2025                          19.70       0
2176                          20.25       0
2250                          25.35       0
2855                          73.35       0
3052                          25.75       0
3118                          52.55       0
4054                          80.85       0
5433                          19.85       0

In [ ]:
idx = dados[dados['Charges.Total'] == ' '].index
dados.loc[idx, "Charges.Total"] = dados.loc[idx, "Charges.Monthly"]

In [ ]:
dados['Charges.Total'] = dados['Charges.Total'].astype('float64')

<ipython-input-21-3f7d7ea2280e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Charges.Total'] = dados['Charges.Total'].astype('float64')

In [ ]:
dados.query('tenure == 0')[['Charges.Total', 'Charges.Monthly', 'tenure']]

      Charges.Total  Charges.Monthly  tenure
945           56.05            56.05       0
1731          20.00            20.00       0
1906          61.90            61.90       0
2025          19.70            19.70       0
2176          20.25            20.25       0
2250          25.35            25.35       0
2855          73.35            73.35       0
3052          25.75            25.75       0
3118          52.55            52.55       0
4054          80.85            80.85       0
5433          19.85            19.85       0

Calculando os gastos diários

In [ ]:
dados['Charges.Daily'] = dados['Charges.Total'] / dados['tenure']


cols = list(dados.columns)
cols.insert(18, cols.pop(cols.index('Charges.Daily')))
dados = dados[cols]

<ipython-input-23-a1b3f8921691>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Charges.Daily'] = dados['Charges.Total'] / dados['tenure']

In [ ]:
dados['Charges.Daily']

0       65.922222
1       60.266667
2       70.212500
3       95.219231
4       89.133333
          ...
7038    57.146154
7039    85.168182
7040    46.375000
7041    69.069403
7042    58.850794
Name: Charges.Daily, Length: 7043, dtype: float64

In [ ]:

dados.to_json("/content/drive/MyDrive/Colab Notebooks/Alura Challenge DS 1/Telco-Customer-Churn-limpeza.json")